import HomePage from '../page/HomePage'
import ElementActions from '../page/ElementActions'

const homePage = new HomePage
const elementActions = new ElementActions

const testData = require ('../fixtures/TestData.json')

describe('Movie Ticket Purchase', () => {
    it('Should allow a user to select a movie, choose a city, theater, and seats, and complete the purchase', () => {
        homePage.navigatorToHomePage()
        elementActions.clickOnTheButton(HomePage.modalCloseButton)
        elementActions.clickOnTheButton(HomePage.signInButton)
        elementActions.writeInTextBox(HomePage.emailInput, testData.MemberEmail)
        elementActions.writeInTextBox(HomePage.passwordInput, testData.MemberPassword)
        elementActions.clickOnTheButton(HomePage.loginButton)
        elementActions.validateNotExist(HomePage.loaderIcon)
        elementActions.validation(HomePage.memberNameText, testData.MemberName)
        elementActions.selectMovie(testData.TitleMovie)
        elementActions.clickOnTheButton(HomePage.selectCityButton)
        elementActions.clickOnTheButton(HomePage.userSelect)
        elementActions.validateNotExist(HomePage.loaderIcon)
        elementActions.clickOnTheButton(HomePage.timeButton)
        elementActions.clickOnTheButton(HomePage.confirmButton)
        elementActions.validateNotExist(HomePage.Icon)
        elementActions.validateNotExist(HomePage.loaderIcon)
        elementActions.clickOnTheButton(HomePage.modalCloseButton)
        elementActions.selectDropDown(HomePage.seatSelect, testData.option)
        elementActions.clickOnTheButton(HomePage.continueButton)
        homePage.selectToSeat(testData.gridRow, testData.gridColumn1)
        homePage.selectToSeat(testData.gridRow, testData.gridColumn2)
        elementActions.validateNotExist(HomePage.loaderIcon)
        elementActions.clickOnTheButton(HomePage.shoppingCartContinueButton)
        elementActions.clickOnTheButton(HomePage.confirmSeatButton)
        elementActions.validateNotExist(HomePage.loaderIcon)
        elementActions.clickOnTheButton(HomePage.selectFoodButton)
        elementActions.clickOnTheButton(HomePage.shoppingCartContinueButton)
        elementActions.clickOnTheButton(HomePage.shoppingCartContinueButton)
        elementActions.clickOnTheButton(HomePage.pymentMethodSelect)
        elementActions.writeInTextBox(HomePage.cardNumberInput, testData.cardNumber)
        elementActions.writeInTextBox(HomePage.cardNameInput, testData.cardName)
        elementActions.writeInTextBox(HomePage.cardSecurityCodeInput, testData.cardSecurityCode)
        elementActions.selectDropDown(HomePage.numberInstallmentsSelect, testData.installments)
        elementActions.clickOnTheCheckbox(HomePage.agreementCheck)
        elementActions.clickOnTheButton(HomePage.shoppingCartContinueButton)
        elementActions.clickOnTheButton(HomePage.confirmPaymentButton)
        elementActions.validateNotExist(HomePage.loaderFinal)
        cy.wait(100000)
        elementActions.validateExist(HomePage.codeQA)
        elementActions.validateTextExist(HomePage.CodeText, testData.codeText)
    })
})